### ISSUE TITLE
[Feature] Add messenger for creating backups

### ISSUE THREAD

**Issue by ToshY** [bastien70/dbsaver#60]
**Request**

Currently database backups are created directly on request, which is blocking. Instead it could be handled more gracefully by using [Messenger](https://symfony.com/doc/current/messenger.html). So instead of directly creating a backup on the button click, we'll dispatch a message containing the information needed to create the backup (e.g. a `Database` entity), and then let the worker handle that job.

**Additional information**
* This would require `symfony/messenger` to be added in composer.
* An additional environment variable `MESSENGER_TRANSPORT_DSN`  to be set by the user.
* Additional information / [links](https://symfony.com/doc/current/messenger.html#supervisor-configuration) need to be supplied in docs on how to set up the workers to execute the jobs.

**Comment by bastien70** [comment]
Hello, this is an interesting idea. Only, it would only work on non-shared hosting

In this case it would be necessary, when installing the project, to ask the customer if he wishes to configure this option, and to do the necessary according to his answer. What do you think @jmsche ?

**Comment by jmsche** [comment]
Would probably require us to install several Messenger adapters.

Not sure it's really useful, as it's only about backups run one by one, not several backups to run at the same time.

**Comment by bastien70** [comment]
@jmsche ?

**Comment by bastien70** [comment]
I close the issue since it is not planned for the moment
