### ISSUE TITLE
[Feature] Replace Gaufrette with Flysystem

### ISSUE THREAD

**Issue by ToshY** [bastien70/dbsaver#61]
**Request**

[Flysystem](https://github.com/thephpleague/flysystem) is a popular and actively maintained library (in contrast to Gaufrette), and is also being used in [SymfonyCasts tutorials](https://symfonycasts.com/screencast/symfony-uploads/flysystem). I think making the switch to Flysystem is not a drastic change and it would probably be more attractive for other potential/future users.

**Additional information**
* [OneupFlysystemBundle](https://github.com/1up-lab/OneupFlysystemBundle) for integration with Symfony

**Comment by bastien70** [comment]
Hello !

Thank you for your proposition. I'm just working on a PR to make this change and at the same time allow the user to define his adapters from the admin dashboard : #58 

So what you are asking here will already merge soon :)
