### ISSUE TITLE
[Bug] Max backups option does not remove oldest backup but newest

### ISSUE THREAD

**Issue by ToshY** [bastien70/dbsaver#63]
**Problem**

The max backups option does not remove the oldest backups when it reaches it specified value, but it removes the most recently created one.

**Reproduce**

1. Create a database and set max backups to for example `5`.
2. Make `5` manual backups and check if this is correctly inserted in the database.

![image](https://user-images.githubusercontent.com/31921460/174444807-412f87ea-e4e7-4589-84ff-b5f79c9d59f6.png)
3. Now make another backup (nr. `6`) and check the database again. 

![image](https://user-images.githubusercontent.com/31921460/174444924-8e0c8ac2-09d2-4d2f-b0e7-89bf8044bd52.png)

No new backup seems to be created and the same backups are still present.

Now, if you set the max backups option for the database to `6`, and then create a new backup, the following happens:

![image](https://user-images.githubusercontent.com/31921460/174445096-c639b015-eed1-494e-bbee-e004a5a85135.png)

It inserted a new backup, _but_ with ID 7.

**Conclusion**

Apparently the check with max backups is done in the `clean` method, which is the root problem of this issue. The implementation with the looping over the backups is incorrect, as it causes the removal of the most recent backup right after creation, which explains the initially strange jump in ID after increasing max backups option.

**Possible solution**

Adding a method to the `BackupRepository` with custom querybuilder for selecting the backups to be removed, and then delete them in the current `clean` method. Or maybe [doctrine collection matching](https://www.doctrine-project.org/projects/doctrine-collections/en/1.6/index.html#collection-methods) could come in handy here. Many different solutions possible.

**Comment by bastien70** [comment]
Hello! Thanks for letting us know! I'm trying to see that once my current PR merges ;)

Otherwise you can also open a PR if you have time :)

**Comment by ToshY** [comment]
@bastien70 Added PR
