### ISSUE TITLE
2FA missing

### ISSUE THREAD

**Issue by vince844** [bastien70/dbsaver#78]
Hi,

Considering the backups are accessible online, are you planning to add 2FA?

**Comment by bastien70** [comment]
Hello,

Yes, good idea. But I don't know when I will have time to do it, I'm quite busy at the moment. In the meantime, if this is urgent for you, PR's welcome :)

**Comment by jmsche** [comment]
Hi @vince844, do you plan to work on this?
Else I could do something in the following days.

**Comment by jmsche** [comment]
Hi @vince844,

This was fixed by #82.
